// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CompiledPDF represents a generated PDF in the output directory
 */
export class CompiledPDF {
    "name": string;
    "path": string;
    "size": number;
    "modified": string;
    "serveUrl": string;
    "metadata": string;

    /** Creates a new CompiledPDF instance. */
    constructor($$source: Partial<CompiledPDF> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("modified" in $$source)) {
            this["modified"] = "";
        }
        if (!("serveUrl" in $$source)) {
            this["serveUrl"] = "";
        }
        if (!("metadata" in $$source)) {
            this["metadata"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CompiledPDF instance from a string or object.
     */
    static createFrom($$source: any = {}): CompiledPDF {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CompiledPDF($$parsedSource as Partial<CompiledPDF>);
    }
}

/**
 * ExportPDFJobs exports selected slide URLs into a single merged editable PDF
 */
export class ExportJob {
    "slideName": string;
    "folderName": string;
    "url": string;

    /**
     * Optional custom interactive DOM state
     */
    "customHtml": string;

    /**
     * Kept for cleanup
     */
    "tempFilename": string;

    "isSwimlane": boolean;

    /** Creates a new ExportJob instance. */
    constructor($$source: Partial<ExportJob> = {}) {
        if (!("slideName" in $$source)) {
            this["slideName"] = "";
        }
        if (!("folderName" in $$source)) {
            this["folderName"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("customHtml" in $$source)) {
            this["customHtml"] = "";
        }
        if (!("tempFilename" in $$source)) {
            this["tempFilename"] = "";
        }
        if (!("isSwimlane" in $$source)) {
            this["isSwimlane"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportJob instance from a string or object.
     */
    static createFrom($$source: any = {}): ExportJob {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExportJob($$parsedSource as Partial<ExportJob>);
    }
}

/**
 * ScanResult represents the scan details
 */
export class ScanResult {
    "parentPath": string;
    "slides": Slide[];
    "hasShared": boolean;
    "serverPort": number;

    /** Creates a new ScanResult instance. */
    constructor($$source: Partial<ScanResult> = {}) {
        if (!("parentPath" in $$source)) {
            this["parentPath"] = "";
        }
        if (!("slides" in $$source)) {
            this["slides"] = [];
        }
        if (!("hasShared" in $$source)) {
            this["hasShared"] = false;
        }
        if (!("serverPort" in $$source)) {
            this["serverPort"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScanResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ScanResult {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("slides" in $$parsedSource) {
            $$parsedSource["slides"] = $$createField1_0($$parsedSource["slides"]);
        }
        return new ScanResult($$parsedSource as Partial<ScanResult>);
    }
}

/**
 * Slide represents a discovered slide
 */
export class Slide {
    "name": string;
    "folderName": string;
    "indexHtml": string;
    "url": string;

    /** Creates a new Slide instance. */
    constructor($$source: Partial<Slide> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("folderName" in $$source)) {
            this["folderName"] = "";
        }
        if (!("indexHtml" in $$source)) {
            this["indexHtml"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Slide instance from a string or object.
     */
    static createFrom($$source: any = {}): Slide {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Slide($$parsedSource as Partial<Slide>);
    }
}

// Private type creation functions
const $$createType0 = Slide.createFrom;
const $$createType1 = $Create.Array($$createType0);
