// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AutoCompileDeckPDF(arg1:Array<main.ExportJob>,arg2:number):Promise<string>;

export function AutoCompileSlidePDF(arg1:main.ExportJob,arg2:number):Promise<string>;

export function CaptureCustomStateHTML(arg1:string,arg2:string):Promise<string>;

export function CleanUpServer():Promise<void>;

export function CleanUpTempHTML(arg1:string,arg2:string):Promise<void>;

export function CompileScreenshot(arg1:main.ExportJob,arg2:string,arg3:number):Promise<string>;

export function CompileSlidesToIDML(arg1:Array<main.ExportJob>,arg2:string,arg3:number):Promise<string>;

export function CompileSlidesToPDF(arg1:Array<main.ExportJob>,arg2:string,arg3:number):Promise<string>;

export function DeleteCompiledPDF(arg1:string):Promise<void>;

export function EnsureOutputDir():Promise<string>;

export function ExtractPDFMetadata(arg1:string):Promise<string>;

export function GenerateDeckAutoSavePath():Promise<string>;

export function GenerateNextSequentialPDFPath():Promise<string>;

export function GetOutputDir():Promise<string>;

export function ListCompiledPDFs():Promise<Array<main.CompiledPDF>>;

export function ScanAndStartServer(arg1:string):Promise<main.ScanResult>;

export function SelectDirectory():Promise<string>;

export function SelectIDMLSavePath(arg1:string):Promise<string>;

export function SelectSavePath(arg1:string):Promise<string>;

export function SelectScreenshotSavePath(arg1:string):Promise<string>;
