// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoCompileDeckPDF(arg1, arg2) {
  return window['go']['main']['App']['AutoCompileDeckPDF'](arg1, arg2);
}

export function AutoCompileSlidePDF(arg1, arg2) {
  return window['go']['main']['App']['AutoCompileSlidePDF'](arg1, arg2);
}

export function AutomateActiveSlide(arg1, arg2) {
  return window['go']['main']['App']['AutomateActiveSlide'](arg1, arg2);
}

export function AutomateDeck(arg1) {
  return window['go']['main']['App']['AutomateDeck'](arg1);
}

export function CaptureCustomStateHTML(arg1, arg2) {
  return window['go']['main']['App']['CaptureCustomStateHTML'](arg1, arg2);
}

export function CleanUpServer() {
  return window['go']['main']['App']['CleanUpServer']();
}

export function CleanUpTempHTML(arg1, arg2) {
  return window['go']['main']['App']['CleanUpTempHTML'](arg1, arg2);
}

export function CombineCompiledPDFs() {
  return window['go']['main']['App']['CombineCompiledPDFs']();
}

export function CompileDeckFromCaptures(arg1, arg2) {
  return window['go']['main']['App']['CompileDeckFromCaptures'](arg1, arg2);
}

export function CompileScreenshot(arg1, arg2, arg3) {
  return window['go']['main']['App']['CompileScreenshot'](arg1, arg2, arg3);
}

export function CompileSingleStateToPDF(arg1, arg2) {
  return window['go']['main']['App']['CompileSingleStateToPDF'](arg1, arg2);
}

export function CompileSlideFromCaptures(arg1, arg2) {
  return window['go']['main']['App']['CompileSlideFromCaptures'](arg1, arg2);
}

export function CompileSlidesToIDML(arg1, arg2, arg3) {
  return window['go']['main']['App']['CompileSlidesToIDML'](arg1, arg2, arg3);
}

export function CompileSlidesToPDF(arg1, arg2, arg3) {
  return window['go']['main']['App']['CompileSlidesToPDF'](arg1, arg2, arg3);
}

export function DeleteCompiledPDF(arg1) {
  return window['go']['main']['App']['DeleteCompiledPDF'](arg1);
}

export function EndPDFSession(arg1) {
  return window['go']['main']['App']['EndPDFSession'](arg1);
}

export function EnsureOutputDir() {
  return window['go']['main']['App']['EnsureOutputDir']();
}

export function ExtractPDFMetadata(arg1) {
  return window['go']['main']['App']['ExtractPDFMetadata'](arg1);
}

export function GenerateDeckAutoSavePath() {
  return window['go']['main']['App']['GenerateDeckAutoSavePath']();
}

export function GenerateNextSequentialPDFPath() {
  return window['go']['main']['App']['GenerateNextSequentialPDFPath']();
}

export function GetOutputDir() {
  return window['go']['main']['App']['GetOutputDir']();
}

export function IsSingleSlidePDF(arg1) {
  return window['go']['main']['App']['IsSingleSlidePDF'](arg1);
}

export function ListCombinedDecks() {
  return window['go']['main']['App']['ListCombinedDecks']();
}

export function ListCompiledPDFs() {
  return window['go']['main']['App']['ListCompiledPDFs']();
}

export function ScanActiveSlide(arg1) {
  return window['go']['main']['App']['ScanActiveSlide'](arg1);
}

export function ScanAndStartServer(arg1) {
  return window['go']['main']['App']['ScanAndStartServer'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectIDMLSavePath(arg1) {
  return window['go']['main']['App']['SelectIDMLSavePath'](arg1);
}

export function SelectSavePath(arg1) {
  return window['go']['main']['App']['SelectSavePath'](arg1);
}

export function SelectScreenshotSavePath(arg1) {
  return window['go']['main']['App']['SelectScreenshotSavePath'](arg1);
}

export function StartPDFSession() {
  return window['go']['main']['App']['StartPDFSession']();
}
